config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "groups#index"
  resources :users, only: [:edit, :update]
  resources :groups, only: [:index, :new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  has_many :users_groups
  has_many :users, through: :users_groups
  has_many :messages

  def show_last_message
    if (last_message = messages.last).present?
      last_message.body? ? last_message.body : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :body, presence: true, unless: :image?
  mount_uploader :image, MessageImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :users_groups
  has_many :groups, through: :users_groups
  has_many :messages
end

app/models/users_group.rb
class UsersGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def new
    @group = Group.new
    @group.users << current_user
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%").where.not(name: current_user.name)
    respond_to do |format|
      format.html
      format.json
    end
  end
  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, { user_ids:[] })
  end
  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    respond_to do |format|
      format.html
      format.json { @new_message = @messages.where('id > ?', params[:msg_id]) }
    end
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group), notice:'メッセージが送信されました。' }
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください'
      render :index
    end
  end

  private
  def message_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id)
  end
  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group, html:{id:"group-form-for"}  do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat_group_name chat-group-form__input', placeholder: 'グループ名を入力してください'

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for:"chat_group_チャットメンバーを追加"}
        チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input.chat-group-form__input#user-search-field{placeholder:'追加したいユーザー名を入力してください', type:'text', name:'keyword'}
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      #group-member-list
        -group.users.each do |user|
          .chat-group-user.clearfix
            %p.chat-group-user__name
              =user.name
            - unless user.id == current_user.id
              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove{data_user_id:"#{user.id}", data_user_name:"#{user.name}"}
                削除
      = f.collection_check_boxes(:user_ids, User.all, :id, :name)

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: {group: @group}

app/views/groups/index.html.haml
.contents
  = render 'shared/side_menu'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'form', locals: {group: @group}

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_messages.html.haml
- @messages.each do |message|
  .message{data_id:"#{message.id}"}
    .message__post-info
      %p.message__post-info--post-user
        = message.user.name
      %p.message__post-info--post-date
        = message.created_at.strftime("%Y/%m/%d(%a) %H:%M:%S")
    -if message.body.present?
      %p.message__post-message
        = message.body
    = image_tag message.image.url if message.image.present?

app/views/messages/index.html.haml
.contents
  = render 'shared/side_menu'
  .content-main
    .main-header
      .main-header__left-box
        %p.main-header__left-box--group-name
          =@group.name
        %p.main-header__left-box--group-members
          Member :
          - @group.users.each do |user|
            =user.name
      -if params[:group_id]
        .main-header__right-box
          = link_to edit_group_path(params[:group_id]) do
            .main-header__right-box--group-edit
              Edit
    .main-body
      .messages#messages
        = render partial: 'messages', locals: {messages: @messages }
    .main-form
      = form_for [@group, @message], html:{class:"form-body"} do |f|
        .new-message
          .new-message__input-box
            = f.text_field :body, class: "new-message__input-box--text", placeholder: 'type a message'
            .new-message__input-box__image-box
              = f.label :image do
                = fa_icon 'fa-image', class: 'fa fa-image fa-lg new-message__input-box__image-box--image'
                = f.file_field :image, class: 'new-message__input-box__image-box--filesend'
          .new-message__input-box--send
            = f.submit 'Send', class:'form-submit'

app/views/shared/_side_menu.html.haml
.content-side
  .side-header
    .side-header__box
      %p.side-header__box--user-name
        = current_user.name
      %ul.side-header__box__menu
        %li.side-header__box__menu--edit-user
          = link_to new_group_path do
            = fa_icon 'edit', class: 'icon'
        %li.side-header__box__menu--add-group
          = link_to edit_user_path(current_user) do
            = fa_icon 'gear', class: 'icon'
  .side-groups
    - current_user.groups.each do |group|
      = link_to group_messages_path(group) do
        .group
          %p.group__group-name
            = group.name
          %p.group__latest-message
            = group.show_last_message

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'